'''
pokefirered map names

'''

pokefirered_map_names = \
{"gMapGroup_00" : {"gMap_00_00" : "UnknownMap_00_00",
                   "gMap_00_01" : "UnknownMap_00_01",
                   "gMap_00_02" : "UnknownMap_00_02",
                   "gMap_00_03" : "UnknownMap_00_03",
                   "gMap_00_04" : "UnknownMap_00_04",
                  },
 "gMapGroup_01" : {"gMap_01_00" : "ViridianForest",
                   "gMap_01_01" : "MtMoon_1F",
                   "gMap_01_02" : "MtMoon_B1F",
                   "gMap_01_03" : "MtMoon_B2F",
                   "gMap_01_04" : "SSAnne_Exterior",
                   "gMap_01_05" : "SSAnne_1F_Corridor",
                   "gMap_01_06" : "SSAnne_2F_Corridor",
                   "gMap_01_07" : "SSAnne_3F_Corridor",
                   "gMap_01_08" : "SSAnne_B1F_Corridor",
                   "gMap_01_09" : "SSAnne_Deck",
                   "gMap_01_10" : "SSAnne_Kitchen",
                   "gMap_01_11" : "SSAnne_CaptainsOffice",
                   "gMap_01_12" : "SSAnne_1F_Room1",
                   "gMap_01_13" : "SSAnne_1F_Room2",
                   "gMap_01_14" : "SSAnne_1F_Room3",
                   "gMap_01_15" : "SSAnne_1F_Room4",
                   "gMap_01_16" : "SSAnne_1F_Room5",
                   "gMap_01_17" : "SSAnne_1F_Room7",
                   "gMap_01_18" : "SSAnne_2F_Room1",
                   "gMap_01_19" : "SSAnne_2F_Room2",
                   "gMap_01_20" : "SSAnne_2F_Room3",
                   "gMap_01_21" : "SSAnne_2F_Room4",
                   "gMap_01_22" : "SSAnne_2F_Room5",
                   "gMap_01_23" : "SSAnne_2F_Room6",
                   "gMap_01_24" : "SSAnne_B1F_Room1",
                   "gMap_01_25" : "SSAnne_B1F_Room2",
                   "gMap_01_26" : "SSAnne_B1F_Room3",
                   "gMap_01_27" : "SSAnne_B1F_Room4",
                   "gMap_01_28" : "SSAnne_B1F_Room5",
                   "gMap_01_29" : "SSAnne_1F_Room6",
                   "gMap_01_30" : "UndergroundPath_NorthEntrance",
                   "gMap_01_31" : "UndergroundPath_NorthSouthTunnel",
                   "gMap_01_32" : "UndergroundPath_SouthEntrance",
                   "gMap_01_33" : "UndergroundPath_WestEntrance",
                   "gMap_01_34" : "UndergroundPath_EastWestTunnel",
                   "gMap_01_35" : "UndergroundPath_EastEntrance",
                   "gMap_01_36" : "DiglettsCave_NorthEntrance",
                   "gMap_01_37" : "DiglettsCave_B1F",
                   "gMap_01_38" : "DiglettsCave_SouthEntrance",
                   "gMap_01_39" : "VictoryRoad_1F",
                   "gMap_01_40" : "VictoryRoad_2F",
                   "gMap_01_41" : "VictoryRoad_3F",
                   "gMap_01_42" : "RocketHideout_B1F",
                   "gMap_01_43" : "RocketHideout_B2F",
                   "gMap_01_44" : "RocketHideout_B3F",
                   "gMap_01_45" : "RocketHideout_B4F",
                   "gMap_01_46" : "RocketHideout_Elevator",
                   "gMap_01_47" : "SilphCo_1F",
                   "gMap_01_48" : "SilphCo_2F",
                   "gMap_01_49" : "SilphCo_3F",
                   "gMap_01_50" : "SilphCo_4F",
                   "gMap_01_51" : "SilphCo_5F",
                   "gMap_01_52" : "SilphCo_6F",
                   "gMap_01_53" : "SilphCo_7F",
                   "gMap_01_54" : "SilphCo_8F",
                   "gMap_01_55" : "SilphCo_9F",
                   "gMap_01_56" : "SilphCo_10F",
                   "gMap_01_57" : "SilphCo_11F",
                   "gMap_01_58" : "SilphCo_Elevator",
                   "gMap_01_59" : "PokemonMansion_1F",
                   "gMap_01_60" : "PokemonMansion_2F",
                   "gMap_01_61" : "PokemonMansion_3F",
                   "gMap_01_62" : "PokemonMansion_B1F",
                   "gMap_01_63" : "SafariZone_Center",
                   "gMap_01_64" : "SafariZone_East",
                   "gMap_01_65" : "SafariZone_North",
                   "gMap_01_66" : "SafariZone_West",
                   "gMap_01_67" : "SafariZone_Building1",
                   "gMap_01_68" : "SafariZone_Building2",
                   "gMap_01_69" : "SafariZone_Building3",
                   "gMap_01_70" : "SafariZone_Building4",
                   "gMap_01_71" : "SafariZone_SecretHouse",
                   "gMap_01_72" : "CeruleanCave_1F",
                   "gMap_01_73" : "CeruleanCave_2F",
                   "gMap_01_74" : "CeruleanCave_B1F",
                   "gMap_01_75" : "PokemonLeague_LoreleisRoom",
                   "gMap_01_76" : "PokemonLeague_BrunosRoom",
                   "gMap_01_77" : "PokemonLeague_AgathasRoom",
                   "gMap_01_78" : "PokemonLeague_LancesRoom",
                   "gMap_01_79" : "PokemonLeague_ChampionsRoom",
                   "gMap_01_80" : "PokemonLeague_HallOfFame",
                   "gMap_01_81" : "RockTunnel_1F",
                   "gMap_01_82" : "RockTunnel_B1F",
                   "gMap_01_83" : "SeafoamIslands_1F",
                   "gMap_01_84" : "SeafoamIslands_B1F",
                   "gMap_01_85" : "SeafoamIslands_B2F",
                   "gMap_01_86" : "SeafoamIslands_B3F",
                   "gMap_01_87" : "SeafoamIslands_B4F",
                   "gMap_01_88" : "PokemonTower_1F",
                   "gMap_01_89" : "PokemonTower_2F",
                   "gMap_01_90" : "PokemonTower_3F",
                   "gMap_01_91" : "PokemonTower_4F",
                   "gMap_01_92" : "PokemonTower_5F",
                   "gMap_01_93" : "PokemonTower_6F",
                   "gMap_01_94" : "PokemonTower_7F",
                   "gMap_01_95" : "PowerPlant",
                   "gMap_01_96" : "MtEmber_RubyPath_B4F",
                   "gMap_01_97" : "MtEmber_Exterior",
                   "gMap_01_98" : "MtEmber_SummitPath_1F",
                   "gMap_01_99" : "MtEmber_SummitPath_2F",
                   "gMap_01_100" : "MtEmber_SummitPath_3F",
                   "gMap_01_101" : "MtEmber_Summit",
                   "gMap_01_102" : "MtEmber_RubyPath_B5F",
                   "gMap_01_103" : "MtEmber_RubyPath_1F",
                   "gMap_01_104" : "MtEmber_RubyPath_B1F",
                   "gMap_01_105" : "MtEmber_RubyPath_B2F",
                   "gMap_01_106" : "MtEmber_RubyPath_B3F",
                   "gMap_01_107" : "MtEmber_RubyPath_B1F_Stairs",
                   "gMap_01_108" : "MtEmber_RubyPath_B2F_Stairs",
                   "gMap_01_109" : "ThreeIsland_BerryForest",
                   "gMap_01_110" : "FourIsland_IcefallCave_Entrance",
                   "gMap_01_111" : "FourIsland_IcefallCave_1F",
                   "gMap_01_112" : "FourIsland_IcefallCave_B1F",
                   "gMap_01_113" : "FourIsland_IcefallCave_Back",
                   "gMap_01_114" : "FiveIsland_RocketWarehouse",
                   "gMap_01_115" : "SixIsland_DottedHole_1F",
                   "gMap_01_116" : "SixIsland_DottedHole_B1F",
                   "gMap_01_117" : "SixIsland_DottedHole_B2F",
                   "gMap_01_118" : "SixIsland_DottedHole_B3F",
                   "gMap_01_119" : "SixIsland_DottedHole_B4F",
                   "gMap_01_120" : "SixIsland_DottedHole_SapphireRoom",
                   "gMap_01_121" : "SixIsland_PatternBush",
                   "gMap_01_122" : "SixIsland_AlteringCave",
                  },
 "gMapGroup_02" : {"gMap_02_00" : "NavelRock_Exterior",
                   "gMap_02_01" : "SevenIsland_TrainerTower_1F",
                   "gMap_02_02" : "SevenIsland_TrainerTower_2F",
                   "gMap_02_03" : "SevenIsland_TrainerTower_3F",
                   "gMap_02_04" : "SevenIsland_TrainerTower_4F",
                   "gMap_02_05" : "SevenIsland_TrainerTower_5F",
                   "gMap_02_06" : "SevenIsland_TrainerTower_6F",
                   "gMap_02_07" : "SevenIsland_TrainerTower_7F",
                   "gMap_02_08" : "SevenIsland_TrainerTower_8F",
                   "gMap_02_09" : "SevenIsland_TrainerTower_Roof",
                   "gMap_02_10" : "SevenIsland_TrainerTower_Lobby",
                   "gMap_02_11" : "SevenIsland_TrainerTower_Elevator",
                   "gMap_02_12" : "FiveIsland_LostCave_Entrance",
                   "gMap_02_13" : "FiveIsland_LostCave_Room1",
                   "gMap_02_14" : "FiveIsland_LostCave_Room2",
                   "gMap_02_15" : "FiveIsland_LostCave_Room3",
                   "gMap_02_16" : "FiveIsland_LostCave_Room4",
                   "gMap_02_17" : "FiveIsland_LostCave_Room5",
                   "gMap_02_18" : "FiveIsland_LostCave_Room6",
                   "gMap_02_19" : "FiveIsland_LostCave_Room7",
                   "gMap_02_20" : "FiveIsland_LostCave_Room8",
                   "gMap_02_21" : "FiveIsland_LostCave_Room9",
                   "gMap_02_22" : "FiveIsland_LostCave_Room10",
                   "gMap_02_23" : "FiveIsland_LostCave_Room11",
                   "gMap_02_24" : "FiveIsland_LostCave_Room12",
                   "gMap_02_25" : "FiveIsland_LostCave_Room13",
                   "gMap_02_26" : "FiveIsland_LostCave_Room14",
                   "gMap_02_27" : "SevenIsland_TanobyRuins_MoneanChamber",
                   "gMap_02_28" : "SevenIsland_TanobyRuins_LiptooChamber",
                   "gMap_02_29" : "SevenIsland_TanobyRuins_WeepthChamber",
                   "gMap_02_30" : "SevenIsland_TanobyRuins_DilfordChamber",
                   "gMap_02_31" : "SevenIsland_TanobyRuins_ScufibChamber",
                   "gMap_02_32" : "SevenIsland_TanobyRuins_RixyChamber",
                   "gMap_02_33" : "SevenIsland_TanobyRuins_ViapoisChamber",
                   "gMap_02_34" : "ThreeIsland_DunsparceTunnel",
                   "gMap_02_35" : "SevenIsland_SeavaultCanyon_TanobyKey",
                   "gMap_02_36" : "NavelRock_1F",
                   "gMap_02_37" : "NavelRock_Summit",
                   "gMap_02_38" : "NavelRock_Base",
                   "gMap_02_39" : "NavelRock_SummitPath_2F",
                   "gMap_02_40" : "NavelRock_SummitPath_3F",
                   "gMap_02_41" : "NavelRock_SummitPath_4F",
                   "gMap_02_42" : "NavelRock_SummitPath_5F",
                   "gMap_02_43" : "NavelRock_BasePath_B1F",
                   "gMap_02_44" : "NavelRock_BasePath_B2F",
                   "gMap_02_45" : "NavelRock_BasePath_B3F",
                   "gMap_02_46" : "NavelRock_BasePath_B4F",
                   "gMap_02_47" : "NavelRock_BasePath_B5F",
                   "gMap_02_48" : "NavelRock_BasePath_B6F",
                   "gMap_02_49" : "NavelRock_BasePath_B7F",
                   "gMap_02_50" : "NavelRock_BasePath_B8F",
                   "gMap_02_51" : "NavelRock_BasePath_B9F",
                   "gMap_02_52" : "NavelRock_BasePath_B10F",
                   "gMap_02_53" : "NavelRock_BasePath_B11F",
                   "gMap_02_54" : "NavelRock_B1F",
                   "gMap_02_55" : "NavelRock_Fork",
                   "gMap_02_56" : "BirthIsland_Exterior",
                   "gMap_02_57" : "OneIsland_KindleRoad_EmberSpa",
                   "gMap_02_58" : "BirthIsland_Harbor",
                   "gMap_02_59" : "NavelRock_Harbor",
                  },
 "gMapGroup_03" : {"gMap_03_00" : "PalletTown",
                   "gMap_03_01" : "ViridianCity",
                   "gMap_03_02" : "PewterCity",
                   "gMap_03_03" : "CeruleanCity",
                   "gMap_03_04" : "LavenderTown",
                   "gMap_03_05" : "VermilionCity",
                   "gMap_03_06" : "CeladonCity",
                   "gMap_03_07" : "FuchsiaCity",
                   "gMap_03_08" : "CinnabarIsland",
                   "gMap_03_09" : "IndigoPlateau_Exterior",
                   "gMap_03_10" : "SaffronCity",
                   "gMap_03_11" : "SaffronCity_Duplicate",
                   "gMap_03_12" : "OneIsland",
                   "gMap_03_13" : "TwoIsland",
                   "gMap_03_14" : "ThreeIsland",
                   "gMap_03_15" : "FourIsland",
                   "gMap_03_16" : "FiveIsland",
                   "gMap_03_17" : "SevenIsland",
                   "gMap_03_18" : "SixIsland",
                   "gMap_03_19" : "Route1",
                   "gMap_03_20" : "Route2",
                   "gMap_03_21" : "Route3",
                   "gMap_03_22" : "Route4",
                   "gMap_03_23" : "Route5",
                   "gMap_03_24" : "Route6",
                   "gMap_03_25" : "Route7",
                   "gMap_03_26" : "Route8",
                   "gMap_03_27" : "Route9",
                   "gMap_03_28" : "Route10",
                   "gMap_03_29" : "Route11",
                   "gMap_03_30" : "Route12",
                   "gMap_03_31" : "Route13",
                   "gMap_03_32" : "Route14",
                   "gMap_03_33" : "Route15",
                   "gMap_03_34" : "Route16",
                   "gMap_03_35" : "Route17",
                   "gMap_03_36" : "Route18",
                   "gMap_03_37" : "Route19",
                   "gMap_03_38" : "Route20",
                   "gMap_03_39" : "Route21_North",
                   "gMap_03_40" : "Route21_South",
                   "gMap_03_41" : "Route22",
                   "gMap_03_42" : "Route23",
                   "gMap_03_43" : "Route24",
                   "gMap_03_44" : "Route25",
                   "gMap_03_45" : "OneIsland_KindleRoad",
                   "gMap_03_46" : "OneIsland_TreasureBeach",
                   "gMap_03_47" : "TwoIsland_CapeBrink",
                   "gMap_03_48" : "ThreeIsland_BondBridge",
                   "gMap_03_49" : "ThreeIsland_Port",
                   "gMap_03_50" : "UnknownMap_03_50",
                   "gMap_03_51" : "UnknownMap_03_51",
                   "gMap_03_52" : "UnknownMap_03_52",
                   "gMap_03_53" : "UnknownMap_03_53",
                   "gMap_03_54" : "FiveIsland_ResortGorgeous",
                   "gMap_03_55" : "FiveIsland_WaterLabyrinth",
                   "gMap_03_56" : "FiveIsland_Meadow",
                   "gMap_03_57" : "FiveIsland_MemorialPillar",
                   "gMap_03_58" : "SixIsland_OutcastIsland",
                   "gMap_03_59" : "SixIsland_GreenPath",
                   "gMap_03_60" : "SixIsland_WaterPath",
                   "gMap_03_61" : "SixIsland_RuinValley",
                   "gMap_03_62" : "SevenIsland_TrainerTower",
                   "gMap_03_63" : "SevenIsland_SevaultCanyon_Entrance",
                   "gMap_03_64" : "SevenIsland_SevaultCanyon",
                   "gMap_03_65" : "SevenIsland_TanobyRuins",
                  },
 "gMapGroup_04" : {"gMap_04_00" : "PalletTown_PlayersHouse_1F",
                   "gMap_04_01" : "PalletTown_PlayersHouse_2F",
                   "gMap_04_02" : "PalletTown_GarysHouse",
                   "gMap_04_03" : "PalletTown_ProfessorOaksLab",
                  },
 "gMapGroup_05" : {"gMap_05_00" : "ViridianCity_House1",
                   "gMap_05_01" : "ViridianCity_Gym",
                   "gMap_05_02" : "ViridianCity_House2",
                   "gMap_05_03" : "ViridianCity_Mart",
                   "gMap_05_04" : "ViridianCity_PokemonCenter_1F",
                   "gMap_05_05" : "ViridianCity_PokemonCenter_2F",
                  },
 "gMapGroup_06" : {"gMap_06_00" : "PewterCity_Museum_1F",
                   "gMap_06_01" : "PewterCity_Museum_2F",
                   "gMap_06_02" : "PewterCity_Gym",
                   "gMap_06_03" : "PewterCity_Mart",
                   "gMap_06_04" : "PewterCity_House1",
                   "gMap_06_05" : "PewterCity_PokemonCenter_1F",
                   "gMap_06_06" : "PewterCity_PokemonCenter_2F",
                   "gMap_06_07" : "PewterCity_House2",
                  },
 "gMapGroup_07" : {"gMap_07_00" : "CeruleanCity_House1",
                   "gMap_07_01" : "CeruleanCity_House2",
                   "gMap_07_02" : "CeruleanCity_House3",
                   "gMap_07_03" : "CeruleanCity_PokemonCenter_1F",
                   "gMap_07_04" : "CeruleanCity_PokemonCenter_2F",
                   "gMap_07_05" : "CeruleanCity_Gym",
                   "gMap_07_06" : "CeruleanCity_BikeShop",
                   "gMap_07_07" : "CeruleanCity_Mart",
                   "gMap_07_08" : "CeruleanCity_House4",
                   "gMap_07_09" : "CeruleanCity_House5",
                  },
 "gMapGroup_08" : {"gMap_08_00" : "LavenderTown_PokemonCenter_1F",
                   "gMap_08_01" : "LavenderTown_PokemonCenter_2F",
                   "gMap_08_02" : "LavenderTown_VolunteerPokemonHouse",
                   "gMap_08_03" : "LavenderTown_House1",
                   "gMap_08_04" : "LavenderTown_House2",
                   "gMap_08_05" : "LavenderTown_Mart",
                  },
 "gMapGroup_09" : {"gMap_09_00" : "VermilionCity_House1",
                   "gMap_09_01" : "VermilionCity_PokemonCenter_1F",
                   "gMap_09_02" : "VermilionCity_PokemonCenter_2F",
                   "gMap_09_03" : "VermilionCity_PokemonFanClub",
                   "gMap_09_04" : "VermilionCity_House2",
                   "gMap_09_05" : "VermilionCity_Mart",
                   "gMap_09_06" : "VermilionCity_Gym",
                   "gMap_09_07" : "VermilionCity_House3",
                  },
 "gMapGroup_10" : {"gMap_10_00" : "CeladonCity_DepartmentStore_1F",
                   "gMap_10_01" : "CeladonCity_DepartmentStore_2F",
                   "gMap_10_02" : "CeladonCity_DepartmentStore_3F",
                   "gMap_10_03" : "CeladonCity_DepartmentStore_4F",
                   "gMap_10_04" : "CeladonCity_DepartmentStore_5F",
                   "gMap_10_05" : "CeladonCity_DepartmentStore_Roof",
                   "gMap_10_06" : "CeladonCity_DepartmentStore_Elevator",
                   "gMap_10_07" : "CeladonCity_Condominiums_1F",
                   "gMap_10_08" : "CeladonCity_Condominiums_2F",
                   "gMap_10_09" : "CeladonCity_Condominiums_3F",
                   "gMap_10_10" : "CeladonCity_Condominiums_Roof",
                   "gMap_10_11" : "CeladonCity_Condominiums_RoofRoom",
                   "gMap_10_12" : "CeladonCity_PokemonCenter_1F",
                   "gMap_10_13" : "CeladonCity_PokemonCenter_2F",
                   "gMap_10_14" : "CeladonCity_GameCorner",
                   "gMap_10_15" : "CeladonCity_GameCorner_PrizeRoom",
                   "gMap_10_16" : "CeladonCity_Gym",
                   "gMap_10_17" : "CeladonCity_Restaurant",
                   "gMap_10_18" : "CeladonCity_House1",
                   "gMap_10_19" : "CeladonCity_Hotel",
                  },
 "gMapGroup_11" : {"gMap_11_00" : "FuchsiaCity_SafariZone_Entrance",
                   "gMap_11_01" : "FuchsiaCity_Mart",
                   "gMap_11_02" : "FuchsiaCity_ZooBuilding",
                   "gMap_11_03" : "FuchsiaCity_Gym",
                   "gMap_11_04" : "FuchsiaCity_House1",
                   "gMap_11_05" : "FuchsiaCity_PokemonCenter_1F",
                   "gMap_11_06" : "FuchsiaCity_PokemonCenter_2F",
                   "gMap_11_07" : "FuchsiaCity_Building1",
                   "gMap_11_08" : "FuchsiaCity_House2",
                   "gMap_11_09" : "FuchsiaCity_House3",
                  },
 "gMapGroup_12" : {"gMap_12_00" : "CinnabarIsland_Gym",
                   "gMap_12_01" : "CinnabarIsland_PokemonLab_Entrance",
                   "gMap_12_02" : "CinnabarIsland_PokemonLab_Lounge",
                   "gMap_12_03" : "CinnabarIsland_PokemonLab_ResearchRoom",
                   "gMap_12_04" : "CinnabarIsland_PokemonLab_ExperimentRoom",
                   "gMap_12_05" : "CinnabarIsland_PokemonCenter_1F",
                   "gMap_12_06" : "CinnabarIsland_PokemonCenter_2F",
                   "gMap_12_07" : "CinnabarIsland_Mart",
                  },
 "gMapGroup_13" : {"gMap_13_00" : "IndigoPlateau_PokemonCenter_1F",
                   "gMap_13_01" : "IndigoPlateau_PokemonCenter_2F",
                  },
 "gMapGroup_14" : {"gMap_14_00" : "SaffronCity_House1_1F",
                   "gMap_14_01" : "SaffronCity_House1_2F",
                   "gMap_14_02" : "SaffronCity_Dojo",
                   "gMap_14_03" : "SaffronCity_Gym",
                   "gMap_14_04" : "SaffronCity_House2",
                   "gMap_14_05" : "SaffronCity_Mart",
                   "gMap_14_06" : "SaffronCity_PokemonCenter_1F",
                   "gMap_14_07" : "SaffronCity_PokemonCenter_2F",
                   "gMap_14_08" : "SaffronCity_House3",
                   "gMap_14_09" : "SaffronCity_PokemonTrainerFanClub",
                  },
 "gMapGroup_15" : {"gMap_15_00" : "Route2_ViridianForest_SouthEntrance",
                   "gMap_15_01" : "Route2_House",
                   "gMap_15_02" : "Route2_EastBuilding",
                   "gMap_15_03" : "Route2_ViridianForest_NorthEntrance",
                  },
 "gMapGroup_16" : {"gMap_16_00" : "Route4_PokemonCenter_1F",
                   "gMap_16_01" : "Route4_PokemonCenter_2F",
                  },
 "gMapGroup_17" : {"gMap_17_00" : "Route5_PokemonDayCare",
                   "gMap_17_01" : "Route5_SouthEntrance",
                  },
 "gMapGroup_18" : {"gMap_18_00" : "Route6_NorthEntrance",
                   "gMap_18_01" : "UnknownMap_18_01",
                  },
 "gMapGroup_19" : {"gMap_19_00" : "Route7_EastEntrance",
                  },
 "gMapGroup_20" : {"gMap_20_00" : "Route8_WestEntrance",
                  },
 "gMapGroup_21" : {"gMap_21_00" : "Route10_PokemonCenter_1F",
                   "gMap_21_01" : "Route10_PokemonCenter_2F",
                  },
 "gMapGroup_22" : {"gMap_22_00" : "Route11_EastEntrance_1F",
                   "gMap_22_01" : "Route11_EastEntrance_2F",
                  },
 "gMapGroup_23" : {"gMap_23_00" : "Route12_NorthEntrance_1F",
                   "gMap_23_01" : "Route12_NorthEntrance_2F",
                   "gMap_23_02" : "Route12_FishingHouse",
                  },
 "gMapGroup_24" : {"gMap_24_00" : "Route15_WestEntrance_1F",
                   "gMap_24_01" : "Route15_WestEntrance_2F",
                  },
 "gMapGroup_25" : {"gMap_25_00" : "Route16_House",
                   "gMap_25_01" : "Route16_NorthEntrance_1F",
                   "gMap_25_02" : "Route16_NorthEntrance_2F",
                  },
 "gMapGroup_26" : {"gMap_26_00" : "Route18_EastEntrance_1F",
                   "gMap_26_01" : "Route18_EastEntrance_2F",
                  },
 "gMapGroup_27" : {"gMap_27_00" : "UnusedHouse_27_00",
                  },
 "gMapGroup_28" : {"gMap_28_00" : "Route22_NorthEntrance",
                  },
 "gMapGroup_29" : {"gMap_29_00" : "UnusedHouse_29_00",
                  },
 "gMapGroup_30" : {"gMap_30_00" : "Route25_SeaCottage",
                  },
 "gMapGroup_31" : {"gMap_31_00" : "SevenIsland_House_Room1",
                   "gMap_31_01" : "SevenIsland_House_Room2",
                   "gMap_31_02" : "SevenIsland_Mart",
                   "gMap_31_03" : "SevenIsland_PokemonCenter_1F",
                   "gMap_31_04" : "SevenIsland_PokemonCenter_2F",
                   "gMap_31_05" : "UnusedHouse_31_05",
                   "gMap_31_06" : "SevenIsland_Harbor",
                  },
 "gMapGroup_32" : {"gMap_32_00" : "OneIsland_PokemonCenter_1F",
                   "gMap_32_01" : "OneIsland_PokemonCenter_2F",
                   "gMap_32_02" : "OneIsland_House1",
                   "gMap_32_03" : "OneIsland_House2",
                   "gMap_32_04" : "OneIsland_Harbor",
                  },
 "gMapGroup_33" : {"gMap_33_00" : "TwoIsland_JoyfulGameCorner",
                   "gMap_33_01" : "TwoIsland_House",
                   "gMap_33_02" : "TwoIsland_PokemonCenter_1F",
                   "gMap_33_03" : "TwoIsland_PokemonCenter_2F",
                   "gMap_33_04" : "TwoIsland_Harbor",
                  },
 "gMapGroup_34" : {"gMap_34_00" : "ThreeIsland_House1",
                   "gMap_34_01" : "ThreeIsland_PokemonCenter_1F",
                   "gMap_34_02" : "ThreeIsland_PokemonCenter_2F",
                   "gMap_34_03" : "ThreeIsland_Mart",
                   "gMap_34_04" : "ThreeIsland_House2",
                   "gMap_34_05" : "ThreeIsland_House3",
                   "gMap_34_06" : "ThreeIsland_House4",
                   "gMap_34_07" : "ThreeIsland_House5",
                  },
 "gMapGroup_35" : {"gMap_35_00" : "FourIsland_PokemonDayCare",
                   "gMap_35_01" : "FourIsland_PokemonCenter_1F",
                   "gMap_35_02" : "FourIsland_PokemonCenter_2F",
                   "gMap_35_03" : "FourIsland_House1",
                   "gMap_35_04" : "FourIsland_LoreleisHouse",
                   "gMap_35_05" : "FourIsland_Harbor",
                   "gMap_35_06" : "FourIsland_House2",
                   "gMap_35_07" : "FourIsland_Mart",
                  },
 "gMapGroup_36" : {"gMap_36_00" : "FiveIsland_PokemonCenter_1F",
                   "gMap_36_01" : "FiveIsland_PokemonCenter_2F",
                   "gMap_36_02" : "FiveIsland_Harbor",
                   "gMap_36_03" : "FiveIsland_House1",
                   "gMap_36_04" : "FiveIsland_House2",
                  },
 "gMapGroup_37" : {"gMap_37_00" : "SixIsland_PokemonCenter_1F",
                   "gMap_37_01" : "SixIsland_PokemonCenter_2F",
                   "gMap_37_02" : "SixIsland_Harbor",
                   "gMap_37_03" : "SixIsland_House",
                   "gMap_37_04" : "SixIsland_Mart",
                  },
 "gMapGroup_38" : {"gMap_38_00" : "ThreeIsland_Harbor",
                  },
 "gMapGroup_39" : {"gMap_39_00" : "FiveIsland_ResortGorgeous_House",
                  },
 "gMapGroup_40" : {"gMap_40_00" : "TwoIsland_CapeBrink_House",
                  },
 "gMapGroup_41" : {"gMap_41_00" : "SixIsland_WaterPath_House1",
                   "gMap_41_01" : "SixIsland_WaterPath_House2",
                  },
 "gMapGroup_42" : {"gMap_42_00" : "SevenIsland_SevaultCanyon_House",
                  }
}
