'''
pokefirered map names

'''

pokefirered_map_groups = \
{"gMapGroup_00" : {"00.00" : "UnknownMap_00_00",
                   "00.01" : "UnknownMap_00_01",
                   "00.02" : "UnknownMap_00_02",
                   "00.03" : "UnknownMap_00_03",
                   "00.04" : "UnknownMap_00_04",
                  },
 "gMapGroup_01" : {"01.00" : "ViridianForest",
                   "01.01" : "MtMoon_1F",
                   "01.02" : "MtMoon_B1F",
                   "01.03" : "MtMoon_B2F",
                   "01.04" : "SSAnne_Exterior",
                   "01.05" : "SSAnne_1F_Corridor",
                   "01.06" : "SSAnne_2F_Corridor",
                   "01.07" : "SSAnne_3F_Corridor",
                   "01.08" : "SSAnne_B1F_Corridor",
                   "01.09" : "SSAnne_Deck",
                   "01.10" : "SSAnne_Kitchen",
                   "01.11" : "SSAnne_CaptainsOffice",
                   "01.12" : "SSAnne_1F_Room1",
                   "01.13" : "SSAnne_1F_Room2",
                   "01.14" : "SSAnne_1F_Room3",
                   "01.15" : "SSAnne_1F_Room4",
                   "01.16" : "SSAnne_1F_Room5",
                   "01.17" : "SSAnne_1F_Room7",
                   "01.18" : "SSAnne_2F_Room1",
                   "01.19" : "SSAnne_2F_Room2",
                   "01.20" : "SSAnne_2F_Room3",
                   "01.21" : "SSAnne_2F_Room4",
                   "01.22" : "SSAnne_2F_Room5",
                   "01.23" : "SSAnne_2F_Room6",
                   "01.24" : "SSAnne_B1F_Room1",
                   "01.25" : "SSAnne_B1F_Room2",
                   "01.26" : "SSAnne_B1F_Room3",
                   "01.27" : "SSAnne_B1F_Room4",
                   "01.28" : "SSAnne_B1F_Room5",
                   "01.29" : "SSAnne_1F_Room6",
                   "01.30" : "UndergroundPath_NorthEntrance",
                   "01.31" : "UndergroundPath_NorthSouthTunnel",
                   "01.32" : "UndergroundPath_SouthEntrance",
                   "01.33" : "UndergroundPath_WestEntrance",
                   "01.34" : "UndergroundPath_EastWestTunnel",
                   "01.35" : "UndergroundPath_EastEntrance",
                   "01.36" : "DiglettsCave_NorthEntrance",
                   "01.37" : "DiglettsCave_B1F",
                   "01.38" : "DiglettsCave_SouthEntrance",
                   "01.39" : "VictoryRoad_1F",
                   "01.40" : "VictoryRoad_2F",
                   "01.41" : "VictoryRoad_3F",
                   "01.42" : "RocketHideout_B1F",
                   "01.43" : "RocketHideout_B2F",
                   "01.44" : "RocketHideout_B3F",
                   "01.45" : "RocketHideout_B4F",
                   "01.46" : "RocketHideout_Elevator",
                   "01.47" : "SilphCo_1F",
                   "01.48" : "SilphCo_2F",
                   "01.49" : "SilphCo_3F",
                   "01.50" : "SilphCo_4F",
                   "01.51" : "SilphCo_5F",
                   "01.52" : "SilphCo_6F",
                   "01.53" : "SilphCo_7F",
                   "01.54" : "SilphCo_8F",
                   "01.55" : "SilphCo_9F",
                   "01.56" : "SilphCo_10F",
                   "01.57" : "SilphCo_11F",
                   "01.58" : "SilphCo_Elevator",
                   "01.59" : "PokemonMansion_1F",
                   "01.60" : "PokemonMansion_2F",
                   "01.61" : "PokemonMansion_3F",
                   "01.62" : "PokemonMansion_B1F",
                   "01.63" : "SafariZone_Center",
                   "01.64" : "SafariZone_East",
                   "01.65" : "SafariZone_North",
                   "01.66" : "SafariZone_West",
                   "01.67" : "SafariZone_Building1",
                   "01.68" : "SafariZone_Building2",
                   "01.69" : "SafariZone_Building3",
                   "01.70" : "SafariZone_Building4",
                   "01.71" : "SafariZone_SecretHouse",
                   "01.72" : "CeruleanCave_1F",
                   "01.73" : "CeruleanCave_2F",
                   "01.74" : "CeruleanCave_B1F",
                   "01.75" : "PokemonLeague_LoreleisRoom",
                   "01.76" : "PokemonLeague_BrunosRoom",
                   "01.77" : "PokemonLeague_AgathasRoom",
                   "01.78" : "PokemonLeague_LancesRoom",
                   "01.79" : "PokemonLeague_ChampionsRoom",
                   "01.80" : "PokemonLeague_HallOfFame",
                   "01.81" : "RockTunnel_1F",
                   "01.82" : "RockTunnel_B1F",
                   "01.83" : "SeafoamIslands_1F",
                   "01.84" : "SeafoamIslands_B1F",
                   "01.85" : "SeafoamIslands_B2F",
                   "01.86" : "SeafoamIslands_B3F",
                   "01.87" : "SeafoamIslands_B4F",
                   "01.88" : "PokemonTower_1F",
                   "01.89" : "PokemonTower_2F",
                   "01.90" : "PokemonTower_3F",
                   "01.91" : "PokemonTower_4F",
                   "01.92" : "PokemonTower_5F",
                   "01.93" : "PokemonTower_6F",
                   "01.94" : "PokemonTower_7F",
                   "01.95" : "PowerPlant",
                   "01.96" : "MtEmber_RubyPath_B4F",
                   "01.97" : "MtEmber_Exterior",
                   "01.98" : "MtEmber_SummitPath_1F",
                   "01.99" : "MtEmber_SummitPath_2F",
                   "01.100" : "MtEmber_SummitPath_3F",
                   "01.101" : "MtEmber_Summit",
                   "01.102" : "MtEmber_RubyPath_B5F",
                   "01.103" : "MtEmber_RubyPath_1F",
                   "01.104" : "MtEmber_RubyPath_B1F",
                   "01.105" : "MtEmber_RubyPath_B2F",
                   "01.106" : "MtEmber_RubyPath_B3F",
                   "01.107" : "MtEmber_RubyPath_B1F_Stairs",
                   "01.108" : "MtEmber_RubyPath_B2F_Stairs",
                   "01.109" : "ThreeIsland_BerryForest",
                   "01.110" : "FourIsland_IcefallCave_Entrance",
                   "01.111" : "FourIsland_IcefallCave_1F",
                   "01.112" : "FourIsland_IcefallCave_B1F",
                   "01.113" : "FourIsland_IcefallCave_Back",
                   "01.114" : "FiveIsland_RocketWarehouse",
                   "01.115" : "SixIsland_DottedHole_1F",
                   "01.116" : "SixIsland_DottedHole_B1F",
                   "01.117" : "SixIsland_DottedHole_B2F",
                   "01.118" : "SixIsland_DottedHole_B3F",
                   "01.119" : "SixIsland_DottedHole_B4F",
                   "01.120" : "SixIsland_DottedHole_SapphireRoom",
                   "01.121" : "SixIsland_PatternBush",
                   "01.122" : "SixIsland_AlteringCave",
                  },
 "gMapGroup_02" : {"02.00" : "NavelRock_Exterior",
                   "02.01" : "SevenIsland_TrainerTower_1F",
                   "02.02" : "SevenIsland_TrainerTower_2F",
                   "02.03" : "SevenIsland_TrainerTower_3F",
                   "02.04" : "SevenIsland_TrainerTower_4F",
                   "02.05" : "SevenIsland_TrainerTower_5F",
                   "02.06" : "SevenIsland_TrainerTower_6F",
                   "02.07" : "SevenIsland_TrainerTower_7F",
                   "02.08" : "SevenIsland_TrainerTower_8F",
                   "02.09" : "SevenIsland_TrainerTower_Roof",
                   "02.10" : "SevenIsland_TrainerTower_Lobby",
                   "02.11" : "SevenIsland_TrainerTower_Elevator",
                   "02.12" : "FiveIsland_LostCave_Entrance",
                   "02.13" : "FiveIsland_LostCave_Room1",
                   "02.14" : "FiveIsland_LostCave_Room2",
                   "02.15" : "FiveIsland_LostCave_Room3",
                   "02.16" : "FiveIsland_LostCave_Room4",
                   "02.17" : "FiveIsland_LostCave_Room5",
                   "02.18" : "FiveIsland_LostCave_Room6",
                   "02.19" : "FiveIsland_LostCave_Room7",
                   "02.20" : "FiveIsland_LostCave_Room8",
                   "02.21" : "FiveIsland_LostCave_Room9",
                   "02.22" : "FiveIsland_LostCave_Room10",
                   "02.23" : "FiveIsland_LostCave_Room11",
                   "02.24" : "FiveIsland_LostCave_Room12",
                   "02.25" : "FiveIsland_LostCave_Room13",
                   "02.26" : "FiveIsland_LostCave_Room14",
                   "02.27" : "SevenIsland_TanobyRuins_MoneanChamber",
                   "02.28" : "SevenIsland_TanobyRuins_LiptooChamber",
                   "02.29" : "SevenIsland_TanobyRuins_WeepthChamber",
                   "02.30" : "SevenIsland_TanobyRuins_DilfordChamber",
                   "02.31" : "SevenIsland_TanobyRuins_ScufibChamber",
                   "02.32" : "SevenIsland_TanobyRuins_RixyChamber",
                   "02.33" : "SevenIsland_TanobyRuins_ViapoisChamber",
                   "02.34" : "ThreeIsland_DunsparceTunnel",
                   "02.35" : "SevenIsland_SeavaultCanyon_TanobyKey",
                   "02.36" : "NavelRock_1F",
                   "02.37" : "NavelRock_Summit",
                   "02.38" : "NavelRock_Base",
                   "02.39" : "NavelRock_SummitPath_2F",
                   "02.40" : "NavelRock_SummitPath_3F",
                   "02.41" : "NavelRock_SummitPath_4F",
                   "02.42" : "NavelRock_SummitPath_5F",
                   "02.43" : "NavelRock_BasePath_B1F",
                   "02.44" : "NavelRock_BasePath_B2F",
                   "02.45" : "NavelRock_BasePath_B3F",
                   "02.46" : "NavelRock_BasePath_B4F",
                   "02.47" : "NavelRock_BasePath_B5F",
                   "02.48" : "NavelRock_BasePath_B6F",
                   "02.49" : "NavelRock_BasePath_B7F",
                   "02.50" : "NavelRock_BasePath_B8F",
                   "02.51" : "NavelRock_BasePath_B9F",
                   "02.52" : "NavelRock_BasePath_B10F",
                   "02.53" : "NavelRock_BasePath_B11F",
                   "02.54" : "NavelRock_B1F",
                   "02.55" : "NavelRock_Fork",
                   "02.56" : "BirthIsland_Exterior",
                   "02.57" : "OneIsland_KindleRoad_EmberSpa",
                   "02.58" : "BirthIsland_Harbor",
                   "02.59" : "NavelRock_Harbor",
                  },
 "gMapGroup_03" : {"03.00" : "PalletTown",
                   "03.01" : "ViridianCity",
                   "03.02" : "PewterCity",
                   "03.03" : "CeruleanCity",
                   "03.04" : "LavenderTown",
                   "03.05" : "VermilionCity",
                   "03.06" : "CeladonCity",
                   "03.07" : "FuchsiaCity",
                   "03.08" : "CinnabarIsland",
                   "03.09" : "IndigoPlateau_Exterior",
                   "03.10" : "SaffronCity_Duplicate",
                   "03.11" : "SaffronCity",
                   "03.12" : "OneIsland",
                   "03.13" : "TwoIsland",
                   "03.14" : "ThreeIsland",
                   "03.15" : "FourIsland",
                   "03.16" : "FiveIsland",
                   "03.17" : "SevenIsland",
                   "03.18" : "SixIsland",
                   "03.19" : "Route1",
                   "03.20" : "Route2",
                   "03.21" : "Route3",
                   "03.22" : "Route4",
                   "03.23" : "Route5",
                   "03.24" : "Route6",
                   "03.25" : "Route7",
                   "03.26" : "Route8",
                   "03.27" : "Route9",
                   "03.28" : "Route10",
                   "03.29" : "Route11",
                   "03.30" : "Route12",
                   "03.31" : "Route13",
                   "03.32" : "Route14",
                   "03.33" : "Route15",
                   "03.34" : "Route16",
                   "03.35" : "Route17",
                   "03.36" : "Route18",
                   "03.37" : "Route19",
                   "03.38" : "Route20",
                   "03.39" : "Route21_North",
                   "03.40" : "Route21_South",
                   "03.41" : "Route22",
                   "03.42" : "Route23",
                   "03.43" : "Route24",
                   "03.44" : "Route25",
                   "03.45" : "OneIsland_KindleRoad",
                   "03.46" : "OneIsland_TreasureBeach",
                   "03.47" : "TwoIsland_CapeBrink",
                   "03.48" : "ThreeIsland_BondBridge",
                   "03.49" : "ThreeIsland_Port",
                   "03.50" : "UnknownMap_03_50",
                   "03.51" : "UnknownMap_03_51",
                   "03.52" : "UnknownMap_03_52",
                   "03.53" : "UnknownMap_03_53",
                   "03.54" : "FiveIsland_ResortGorgeous",
                   "03.55" : "FiveIsland_WaterLabyrinth",
                   "03.56" : "FiveIsland_Meadow",
                   "03.57" : "FiveIsland_MemorialPillar",
                   "03.58" : "SixIsland_OutcastIsland",
                   "03.59" : "SixIsland_GreenPath",
                   "03.60" : "SixIsland_WaterPath",
                   "03.61" : "SixIsland_RuinValley",
                   "03.62" : "SevenIsland_TrainerTower",
                   "03.63" : "SevenIsland_SevaultCanyon_Entrance",
                   "03.64" : "SevenIsland_SevaultCanyon",
                   "03.65" : "SevenIsland_TanobyRuins",
                  },
 "gMapGroup_04" : {"04.00" : "PalletTown_PlayersHouse_1F",
                   "04.01" : "PalletTown_PlayersHouse_2F",
                   "04.02" : "PalletTown_GarysHouse",
                   "04.03" : "PalletTown_ProfessorOaksLab",
                  },
 "gMapGroup_05" : {"05.00" : "ViridianCity_House1",
                   "05.01" : "ViridianCity_Gym",
                   "05.02" : "ViridianCity_House2",
                   "05.03" : "ViridianCity_Mart",
                   "05.04" : "ViridianCity_PokemonCenter_1F",
                   "05.05" : "ViridianCity_PokemonCenter_2F",
                  },
 "gMapGroup_06" : {"06.00" : "PewterCity_Museum_1F",
                   "06.01" : "PewterCity_Museum_2F",
                   "06.02" : "PewterCity_Gym",
                   "06.03" : "PewterCity_Mart",
                   "06.04" : "PewterCity_House1",
                   "06.05" : "PewterCity_PokemonCenter_1F",
                   "06.06" : "PewterCity_PokemonCenter_2F",
                   "06.07" : "PewterCity_House2",
                  },
 "gMapGroup_07" : {"07.00" : "CeruleanCity_House1",
                   "07.01" : "CeruleanCity_House2",
                   "07.02" : "CeruleanCity_House3",
                   "07.03" : "CeruleanCity_PokemonCenter_1F",
                   "07.04" : "CeruleanCity_PokemonCenter_2F",
                   "07.05" : "CeruleanCity_Gym",
                   "07.06" : "CeruleanCity_BikeShop",
                   "07.07" : "CeruleanCity_Mart",
                   "07.08" : "CeruleanCity_House4",
                   "07.09" : "CeruleanCity_House5",
                  },
 "gMapGroup_08" : {"08.00" : "LavenderTown_PokemonCenter_1F",
                   "08.01" : "LavenderTown_PokemonCenter_2F",
                   "08.02" : "LavenderTown_VolunteerPokemonHouse",
                   "08.03" : "LavenderTown_House1",
                   "08.04" : "LavenderTown_House2",
                   "08.05" : "LavenderTown_Mart",
                  },
 "gMapGroup_09" : {"09.00" : "VermilionCity_House1",
                   "09.01" : "VermilionCity_PokemonCenter_1F",
                   "09.02" : "VermilionCity_PokemonCenter_2F",
                   "09.03" : "VermilionCity_PokemonFanClub",
                   "09.04" : "VermilionCity_House2",
                   "09.05" : "VermilionCity_Mart",
                   "09.06" : "VermilionCity_Gym",
                   "09.07" : "VermilionCity_House3",
                  },
 "gMapGroup_10" : {"10.00" : "CeladonCity_DepartmentStore_1F",
                   "10.01" : "CeladonCity_DepartmentStore_2F",
                   "10.02" : "CeladonCity_DepartmentStore_3F",
                   "10.03" : "CeladonCity_DepartmentStore_4F",
                   "10.04" : "CeladonCity_DepartmentStore_5F",
                   "10.05" : "CeladonCity_DepartmentStore_Roof",
                   "10.06" : "CeladonCity_DepartmentStore_Elevator",
                   "10.07" : "CeladonCity_Condominiums_1F",
                   "10.08" : "CeladonCity_Condominiums_2F",
                   "10.09" : "CeladonCity_Condominiums_3F",
                   "10.10" : "CeladonCity_Condominiums_Roof",
                   "10.11" : "CeladonCity_Condominiums_RoofRoom",
                   "10.12" : "CeladonCity_PokemonCenter_1F",
                   "10.13" : "CeladonCity_PokemonCenter_2F",
                   "10.14" : "CeladonCity_GameCorner",
                   "10.15" : "CeladonCity_GameCorner_PrizeRoom",
                   "10.16" : "CeladonCity_Gym",
                   "10.17" : "CeladonCity_Restaurant",
                   "10.18" : "CeladonCity_House1",
                   "10.19" : "CeladonCity_Hotel",
                  },
 "gMapGroup_11" : {"11.00" : "FuchsiaCity_SafariZone_Entrance",
                   "11.01" : "FuchsiaCity_Mart",
                   "11.02" : "FuchsiaCity_ZooBuilding",
                   "11.03" : "FuchsiaCity_Gym",
                   "11.04" : "FuchsiaCity_House1",
                   "11.05" : "FuchsiaCity_PokemonCenter_1F",
                   "11.06" : "FuchsiaCity_PokemonCenter_2F",
                   "11.07" : "FuchsiaCity_Building1",
                   "11.08" : "FuchsiaCity_House2",
                   "11.09" : "FuchsiaCity_House3",
                  },
 "gMapGroup_12" : {"12.00" : "CinnabarIsland_Gym",
                   "12.01" : "CinnabarIsland_PokemonLab_Entrance",
                   "12.02" : "CinnabarIsland_PokemonLab_Lounge",
                   "12.03" : "CinnabarIsland_PokemonLab_ResearchRoom",
                   "12.04" : "CinnabarIsland_PokemonLab_ExperimentRoom",
                   "12.05" : "CinnabarIsland_PokemonCenter_1F",
                   "12.06" : "CinnabarIsland_PokemonCenter_2F",
                   "12.07" : "CinnabarIsland_Mart",
                  },
 "gMapGroup_13" : {"13.00" : "IndigoPlateau_PokemonCenter_1F",
                   "13.01" : "IndigoPlateau_PokemonCenter_2F",
                  },
 "gMapGroup_14" : {"14.00" : "SaffronCity_House1_1F",
                   "14.01" : "SaffronCity_House1_2F",
                   "14.02" : "SaffronCity_Dojo",
                   "14.03" : "SaffronCity_Gym",
                   "14.04" : "SaffronCity_House2",
                   "14.05" : "SaffronCity_Mart",
                   "14.06" : "SaffronCity_PokemonCenter_1F",
                   "14.07" : "SaffronCity_PokemonCenter_2F",
                   "14.08" : "SaffronCity_House3",
                   "14.09" : "SaffronCity_PokemonTrainerFanClub",
                  },
 "gMapGroup_15" : {"15.00" : "Route2_ViridianForest_SouthEntrance",
                   "15.01" : "Route2_House",
                   "15.02" : "Route2_EastBuilding",
                   "15.03" : "Route2_ViridianForest_NorthEntrance",
                  },
 "gMapGroup_16" : {"16.00" : "Route4_PokemonCenter_1F",
                   "16.01" : "Route4_PokemonCenter_2F",
                  },
 "gMapGroup_17" : {"17.00" : "Route5_PokemonDayCare",
                   "17.01" : "Route5_SouthEntrance",
                  },
 "gMapGroup_18" : {"18.00" : "Route6_NorthEntrance",
                   "18.01" : "UnknownMap_18_01",
                  },
 "gMapGroup_19" : {"19.00" : "Route7_EastEntrance",
                  },
 "gMapGroup_20" : {"20.00" : "Route8_WestEntrance",
                  },
 "gMapGroup_21" : {"21.00" : "Route10_PokemonCenter_1F",
                   "21.01" : "Route10_PokemonCenter_2F",
                  },
 "gMapGroup_22" : {"22.00" : "Route11_EastEntrance_1F",
                   "22.01" : "Route11_EastEntrance_2F",
                  },
 "gMapGroup_23" : {"23.00" : "Route12_NorthEntrance_1F",
                   "23.01" : "Route12_NorthEntrance_2F",
                   "23.02" : "Route12_FishingHouse",
                  },
 "gMapGroup_24" : {"24.00" : "Route15_WestEntrance_1F",
                   "24.01" : "Route15_WestEntrance_2F",
                  },
 "gMapGroup_25" : {"25.00" : "Route16_House",
                   "25.01" : "Route16_NorthEntrance_1F",
                   "25.02" : "Route16_NorthEntrance_2F",
                  },
 "gMapGroup_26" : {"26.00" : "Route18_EastEntrance_1F",
                   "26.01" : "Route18_EastEntrance_2F",
                  },
 "gMapGroup_27" : {"27.00" : "UnusedHouse_27_00",
                  },
 "gMapGroup_28" : {"28.00" : "Route22_NorthEntrance",
                  },
 "gMapGroup_29" : {"29.00" : "UnusedHouse_29_00",
                  },
 "gMapGroup_30" : {"30.00" : "Route25_SeaCottage",
                  },
 "gMapGroup_31" : {"31.00" : "SevenIsland_House_Room1",
                   "31.01" : "SevenIsland_House_Room2",
                   "31.02" : "SevenIsland_Mart",
                   "31.03" : "SevenIsland_PokemonCenter_1F",
                   "31.04" : "SevenIsland_PokemonCenter_2F",
                   "31.05" : "UnusedHouse_31_05",
                   "31.06" : "SevenIsland_Harbor",
                  },
 "gMapGroup_32" : {"32.00" : "OneIsland_PokemonCenter_1F",
                   "32.01" : "OneIsland_PokemonCenter_2F",
                   "32.02" : "OneIsland_House1",
                   "32.03" : "OneIsland_House2",
                   "32.04" : "OneIsland_Harbor",
                  },
 "gMapGroup_33" : {"33.00" : "TwoIsland_JoyfulGameCorner",
                   "33.01" : "TwoIsland_House",
                   "33.02" : "TwoIsland_PokemonCenter_1F",
                   "33.03" : "TwoIsland_PokemonCenter_2F",
                   "33.04" : "TwoIsland_Harbor",
                  },
 "gMapGroup_34" : {"34.00" : "ThreeIsland_House1",
                   "34.01" : "ThreeIsland_PokemonCenter_1F",
                   "34.02" : "ThreeIsland_PokemonCenter_2F",
                   "34.03" : "ThreeIsland_Mart",
                   "34.04" : "ThreeIsland_House2",
                   "34.05" : "ThreeIsland_House3",
                   "34.06" : "ThreeIsland_House4",
                   "34.07" : "ThreeIsland_House5",
                  },
 "gMapGroup_35" : {"35.00" : "FourIsland_PokemonDayCare",
                   "35.01" : "FourIsland_PokemonCenter_1F",
                   "35.02" : "FourIsland_PokemonCenter_2F",
                   "35.03" : "FourIsland_House1",
                   "35.04" : "FourIsland_LoreleisHouse",
                   "35.05" : "FourIsland_Harbor",
                   "35.06" : "FourIsland_House2",
                   "35.07" : "FourIsland_Mart",
                  },
 "gMapGroup_36" : {"36.00" : "FiveIsland_PokemonCenter_1F",
                   "36.01" : "FiveIsland_PokemonCenter_2F",
                   "36.02" : "FiveIsland_Harbor",
                   "36.03" : "FiveIsland_House1",
                   "36.04" : "FiveIsland_House2",
                  },
 "gMapGroup_37" : {"37.00" : "SixIsland_PokemonCenter_1F",
                   "37.01" : "SixIsland_PokemonCenter_2F",
                   "37.02" : "SixIsland_Harbor",
                   "37.03" : "SixIsland_House",
                   "37.04" : "SixIsland_Mart",
                  },
 "gMapGroup_38" : {"38.00" : "ThreeIsland_Harbor",
                  },
 "gMapGroup_39" : {"39.00" : "FiveIsland_ResortGorgeous_House",
                  },
 "gMapGroup_40" : {"40.00" : "TwoIsland_CapeBrink_House",
                  },
 "gMapGroup_41" : {"41.00" : "SixIsland_WaterPath_House1",
                   "41.01" : "SixIsland_WaterPath_House2",
                  },
 "gMapGroup_42" : {"42.00" : "SevenIsland_SevaultCanyon_House",
                  }
}

pokefirered_map_names = {}
for group, maps in pokefirered_map_groups.items():
    pokefirered_map_names.update({key : value for key, value in maps.items()})


